Limit python int bit_length
Avoid error when passed to pybind-wrapped constructor that expects an int

Previously:

FAILED tests/test_relative_free_energy.py::test_steps_per_frames - TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. timemachine.lib.custom_ops.LangevinIntegrator(masses: numpy.ndarray[numpy.float64], temperature: float, dt: float, friction: float, seed: int)
Invoked with: array([31.421, 12.011, 12.011, 12.011,  9.995,  9.995, 12.011, 15.999, 12.011,  9.995, 12.011,  9.995, 12.011, 12.011,  9.995, 32.067, 15.999, 15.999,  9.995, 18.998, 18.998, 35.453, 13.983, 14.007,  3.024,  3.024,  3.024,  3.024,  3.024, 18.998,  3.024,  3.024,  3.024,  3.024, 14.007]), 300, 0.0025, 1.0, -5862718174732992435